exclude_paths:
 - "/vendor/*"
engines:
  phpcodesniffer-drupal:
    enabled: true
    config:
      file_extensions: "php,module,inc,install,test,profile,theme,js,css,info,txt,md"
      standard: "Drupal,DrupalPractice"
ratings:
  paths:
  - "**.php"
  - "**.module"
  - "**.inc"
  - "**.install"
  - "**.test"
  - "**.profile"
  - "**.theme"
  - "**.js"
  - "**.css"
  - "**.info"
  - "**.txt"
  - "**.md"
